annotations:
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.31.4
description: A Library Helm Chart for grouping common logic between bitnami charts. This chart is not deployable by itself.
keywords:
  - common
name: common
type: library
version: 2.31.4
